title: This Is Me :) 
logo: /assets/img/me.png
description: I am a PhD. Candidate of Computer Science at University of Georgia, Department of Computer Science.
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
